title: Digital Madman
description: Webdeveloper
url: www.digitalmadman.nl

permalink: /blog/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: "post"



collections:
  products:
    output: true
    permalink: /products/:title/
